name: Create Tag

on:
  push:
    branches:
      - main
      - autotag-update

permissions:
  actions: read
  contents: read
  pull-requests: write
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto Tag
        uses: phish108/autotag-action@1.1.52
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          with-v: true
